itcl::class SCIRun_ChangeMesh_CreatePolarProjectionOnImage {
    inherit Module
     constructor { {args ""} } {
        eval configure $args
        set name CreatePolarProjectionOnImage
        set_defaults
    }

    method set_defaults {} {
    }

    method ui {} {
        set w .ui[modname]
        if {[winfo exists $w]} {
            return
        }
        toplevel $w
        label $w.row1 -text "This GUI was auto-generated by the Component Wizard."
        label $w.row2 -text {edit the file "/Users/jeroen/projects/scirun/trunk/src/Dataflow/GUI/CreatePolarProjectionOnImage.tcl" to modify it.}
        pack $w.row1 $w.row2 -side top -padx 10 -pady 10

        makeSciButtonPanel $w $w $this
        moveToCursor $w
    }
}


