/*
  For more information, please see: http://software.sci.utah.edu
  
  The MIT License

  Copyright (c) 2009 Scientific Computing and Imaging Institute,
  University of Utah.


  Permission is hereby granted, free of charge, to any person obtaining a 
  copy of this software and associated documentation files (the "Software"),
  to deal in the Software without restriction, including without limitation 
  the rights to use, copy, modify, merge, publish, distribute, sublicense, 
  and/or sell copies of the Software, and to permit persons to whom the 
  Software is furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included 
  in all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
  DEALINGS IN THE SOFTWARE.
*/

/////////////////////////////////////////////////////////////////////////////
// Name:        arithmeticvolume.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     20/08/2007 08:51:42
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 20/08/2007 08:51:42

#ifndef _ARITHMETICVOLUME_H_
#define _ARITHMETICVOLUME_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
#include "wx/spinctrl.h"
////@end includes
#include "wx/spinctrl.h"

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxSpinCtrl;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_ARITHMETICVOLUME 10041
#define SYMBOL_ARITHMETICVOLUME_STYLE 0
#define SYMBOL_ARITHMETICVOLUME_TITLE _("ArithmeticVolume")
#define SYMBOL_ARITHMETICVOLUME_IDNAME ID_ARITHMETICVOLUME
#define SYMBOL_ARITHMETICVOLUME_SIZE wxSize(200, -1)
#define SYMBOL_ARITHMETICVOLUME_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * ArithmeticVolume class declaration
 */

class ArithmeticVolume: public wxPanel
{
  DECLARE_DYNAMIC_CLASS( ArithmeticVolume )
  DECLARE_EVENT_TABLE()

public:
  /// Constructors
  ArithmeticVolume();
  ArithmeticVolume( wxWindow* parent, wxWindowID id = SYMBOL_ARITHMETICVOLUME_IDNAME, const wxPoint& pos = SYMBOL_ARITHMETICVOLUME_POSITION, const wxSize& size = SYMBOL_ARITHMETICVOLUME_SIZE, long style = SYMBOL_ARITHMETICVOLUME_STYLE );

  /// Creation
  bool Create( wxWindow* parent, wxWindowID id = SYMBOL_ARITHMETICVOLUME_IDNAME, const wxPoint& pos = SYMBOL_ARITHMETICVOLUME_POSITION, const wxSize& size = SYMBOL_ARITHMETICVOLUME_SIZE, long style = SYMBOL_ARITHMETICVOLUME_STYLE );

  /// Destructor
  ~ArithmeticVolume();

  /// Initialises member variables
  void Init();

  /// Creates the controls and sizers
  void CreateControls();
  void OnSetInputs( wxCommandEvent& event );
  void OnStartButtonClick( wxCommandEvent& event );	
  void OnCloseButtonClick( wxCommandEvent& event );

  ////@begin ArithmeticVolume event handler declarations

  ////@end ArithmeticVolume event handler declarations

  ////@begin ArithmeticVolume member function declarations

  /// Retrieves bitmap resources
  wxBitmap GetBitmapResource( const wxString& name );

  /// Retrieves icon resources
  wxIcon GetIconResource( const wxString& name );
  ////@end ArithmeticVolume member function declarations

  /// Should we show tooltips?
  static bool ShowToolTips();

  ////@begin ArithmeticVolume member variables
  wxChoice* mInput1;
  wxChoice* mInput2;
  wxChoice* mOperation;
  ////@end ArithmeticVolume member variables
};

#endif
// _ARITHMETICVOLUME_H_
