/*
  For more information, please see: http://software.sci.utah.edu
  
  The MIT License

  Copyright (c) 2009 Scientific Computing and Imaging Institute,
  University of Utah.


  Permission is hereby granted, free of charge, to any person obtaining a 
  copy of this software and associated documentation files (the "Software"),
  to deal in the Software without restriction, including without limitation 
  the rights to use, copy, modify, merge, publish, distribute, sublicense, 
  and/or sell copies of the Software, and to permit persons to whom the 
  Software is furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included 
  in all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
  DEALINGS IN THE SOFTWARE.
*/

/////////////////////////////////////////////////////////////////////////////
// Name:        fliptool.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     27/08/2007 09:39:40
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 27/08/2007 09:39:40

#ifndef _FLIPTOOL_H_
#define _FLIPTOOL_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_FLIPTOOL 10031
#define SYMBOL_FLIPTOOL_STYLE 0
#define SYMBOL_FLIPTOOL_TITLE _("FlipTool")
#define SYMBOL_FLIPTOOL_IDNAME ID_FLIPTOOL
#define SYMBOL_FLIPTOOL_SIZE wxSize(200, -1)
#define SYMBOL_FLIPTOOL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * FlipTool class declaration
 */

class FlipTool: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( FlipTool )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    FlipTool();
    FlipTool( wxWindow* parent, wxWindowID id = SYMBOL_FLIPTOOL_IDNAME, const wxPoint& pos = SYMBOL_FLIPTOOL_POSITION, const wxSize& size = SYMBOL_FLIPTOOL_SIZE, long style = SYMBOL_FLIPTOOL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_FLIPTOOL_IDNAME, const wxPoint& pos = SYMBOL_FLIPTOOL_POSITION, const wxSize& size = SYMBOL_FLIPTOOL_SIZE, long style = SYMBOL_FLIPTOOL_STYLE );

    /// Destructor
    ~FlipTool();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();
	void OnFlipCoronalButtonClick( wxCommandEvent& event );
	void OnFlipAxialButtonClick( wxCommandEvent& event );
	void OnFlipSagitalButtonClick( wxCommandEvent& event );
	void OnCloseButtonClick( wxCommandEvent& event );

////@begin FlipTool event handler declarations

////@end FlipTool event handler declarations

////@begin FlipTool member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end FlipTool member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin FlipTool member variables
////@end FlipTool member variables
};

#endif
    // _FLIPTOOL_H_
