/*
  For more information, please see: http://software.sci.utah.edu
  
  The MIT License

  Copyright (c) 2009 Scientific Computing and Imaging Institute,
  University of Utah.


  Permission is hereby granted, free of charge, to any person obtaining a 
  copy of this software and associated documentation files (the "Software"),
  to deal in the Software without restriction, including without limitation 
  the rights to use, copy, modify, merge, publish, distribute, sublicense, 
  and/or sell copies of the Software, and to permit persons to whom the 
  Software is furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included 
  in all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
  DEALINGS IN THE SOFTWARE.
*/

/////////////////////////////////////////////////////////////////////////////
// Name:        inverttool.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     27/08/2007 09:39:40
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 27/08/2007 09:39:40

#ifndef _INVERTTOOL_H_
#define _INVERTTOOL_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_INVERTTOOL 10031
#define SYMBOL_INVERTTOOL_STYLE 0
#define SYMBOL_INVERTTOOL_TITLE _("InvertTool")
#define SYMBOL_INVERTTOOL_IDNAME ID_INVERTTOOL
#define SYMBOL_INVERTTOOL_SIZE wxSize(200, -1)
#define SYMBOL_INVERTTOOL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * InvertTool class declaration
 */

class InvertTool: public wxPanel
{    
  DECLARE_DYNAMIC_CLASS( InvertTool )
    DECLARE_EVENT_TABLE()

    public:
  /// Constructors
  InvertTool();
  InvertTool( wxWindow* parent, wxWindowID id = SYMBOL_INVERTTOOL_IDNAME, const wxPoint& pos = SYMBOL_INVERTTOOL_POSITION, const wxSize& size = SYMBOL_INVERTTOOL_SIZE, long style = SYMBOL_INVERTTOOL_STYLE );

  /// Creation
  bool Create( wxWindow* parent, wxWindowID id = SYMBOL_INVERTTOOL_IDNAME, const wxPoint& pos = SYMBOL_INVERTTOOL_POSITION, const wxSize& size = SYMBOL_INVERTTOOL_SIZE, long style = SYMBOL_INVERTTOOL_STYLE );

  /// Destructor
  ~InvertTool();

  /// Initialises member variables
  void Init();

  /// Creates the controls and sizers
  void CreateControls();
  void OnInvertButtonClick( wxCommandEvent& event );
  void OnCloseButtonClick ( wxCommandEvent& event );

  ////@begin InvertTool event handler declarations

  ////@end InvertTool event handler declarations

  ////@begin InvertTool member function declarations

  /// Retrieves bitmap resources
  wxBitmap GetBitmapResource( const wxString& name );

  /// Retrieves icon resources
  wxIcon GetIconResource( const wxString& name );
  ////@end InvertTool member function declarations

  /// Should we show tooltips?
  static bool ShowToolTips();

  ////@begin InvertTool member variables
  ////@end InvertTool member variables
};

#endif
// _INVERTTOOL_H_
