/*
  For more information, please see: http://software.sci.utah.edu
  
  The MIT License

  Copyright (c) 2009 Scientific Computing and Imaging Institute,
  University of Utah.


  Permission is hereby granted, free of charge, to any person obtaining a 
  copy of this software and associated documentation files (the "Software"),
  to deal in the Software without restriction, including without limitation 
  the rights to use, copy, modify, merge, publish, distribute, sublicense, 
  and/or sell copies of the Software, and to permit persons to whom the 
  Software is furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included 
  in all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
  DEALINGS IN THE SOFTWARE.
*/

/////////////////////////////////////////////////////////////////////////////
// Name:        itkcurvatureanistopricdiffusionfilter.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     14/08/2007 13:01:25
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 14/08/2007 13:01:25

#ifndef _ITKCURVATUREANISTOPRICDIFFUSIONFILTER_H_
#define _ITKCURVATUREANISTOPRICDIFFUSIONFILTER_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
#include "wx/spinctrl.h"
#include "wx/valtext.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxSpinCtrl;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_ITKCURVATUREANISTOPRICDIFFUSIONFILTER 10012
#define SYMBOL_ITKCURVATUREANISTOPRICDIFFUSIONFILTER_STYLE 0
#define SYMBOL_ITKCURVATUREANISTOPRICDIFFUSIONFILTER_TITLE _("ITKCurvatureAnistopricDiffusionFilter")
#define SYMBOL_ITKCURVATUREANISTOPRICDIFFUSIONFILTER_IDNAME ID_ITKCURVATUREANISTOPRICDIFFUSIONFILTER
#define SYMBOL_ITKCURVATUREANISTOPRICDIFFUSIONFILTER_SIZE wxSize(200, -1)
#define SYMBOL_ITKCURVATUREANISTOPRICDIFFUSIONFILTER_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * ITKCurvatureAnistopricDiffusionFilter class declaration
 */

class ITKCurvatureAnistopricDiffusionFilter: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( ITKCurvatureAnistopricDiffusionFilter )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ITKCurvatureAnistopricDiffusionFilter();
    ITKCurvatureAnistopricDiffusionFilter( wxWindow* parent, wxWindowID id = SYMBOL_ITKCURVATUREANISTOPRICDIFFUSIONFILTER_IDNAME, const wxPoint& pos = SYMBOL_ITKCURVATUREANISTOPRICDIFFUSIONFILTER_POSITION, const wxSize& size = SYMBOL_ITKCURVATUREANISTOPRICDIFFUSIONFILTER_SIZE, long style = SYMBOL_ITKCURVATUREANISTOPRICDIFFUSIONFILTER_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_ITKCURVATUREANISTOPRICDIFFUSIONFILTER_IDNAME, const wxPoint& pos = SYMBOL_ITKCURVATUREANISTOPRICDIFFUSIONFILTER_POSITION, const wxSize& size = SYMBOL_ITKCURVATUREANISTOPRICDIFFUSIONFILTER_SIZE, long style = SYMBOL_ITKCURVATUREANISTOPRICDIFFUSIONFILTER_STYLE );

    /// Destructor
    ~ITKCurvatureAnistopricDiffusionFilter();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();
	void OnStartButtonClick( wxCommandEvent& event );
	void OnStopButtonClick( wxCommandEvent& event );
	void OnCloseButtonClick( wxCommandEvent& event );
	void OnSetProgress( wxCommandEvent& event );

////@begin ITKCurvatureAnistopricDiffusionFilter event handler declarations

////@end ITKCurvatureAnistopricDiffusionFilter event handler declarations

////@begin ITKCurvatureAnistopricDiffusionFilter member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ITKCurvatureAnistopricDiffusionFilter member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin ITKCurvatureAnistopricDiffusionFilter member variables
    wxSpinCtrl* mIterations;
    wxTextCtrl* mTimeSteps;
    wxSpinCtrl* mConductance;
    wxGauge* mPercentage;
////@end ITKCurvatureAnistopricDiffusionFilter member variables

    wxWindowDisabler *disabler_;
};

#endif
    // _ITKCURVATUREANISTOPRICDIFFUSIONFILTER_H_
