/*
  For more information, please see: http://software.sci.utah.edu
  
  The MIT License

  Copyright (c) 2009 Scientific Computing and Imaging Institute,
  University of Utah.


  Permission is hereby granted, free of charge, to any person obtaining a 
  copy of this software and associated documentation files (the "Software"),
  to deal in the Software without restriction, including without limitation 
  the rights to use, copy, modify, merge, publish, distribute, sublicense, 
  and/or sell copies of the Software, and to permit persons to whom the 
  Software is furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included 
  in all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
  DEALINGS IN THE SOFTWARE.
*/

/////////////////////////////////////////////////////////////////////////////
// Name:        itkconfidenceconnectedfilter.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     14/08/2007 13:04:00
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 14/08/2007 13:04:00

#ifndef _ITKCONFIDENCECONNECTEDFILTER_H_
#define _ITKCONFIDENCECONNECTEDFILTER_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
#include "wx/spinctrl.h"
#include "wx/valtext.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxSpinCtrl;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_ITKCONFIDENCECONNECTEDFILTER 10012
#define SYMBOL_ITKCONFIDENCECONNECTEDFILTER_STYLE 0
#define SYMBOL_ITKCONFIDENCECONNECTEDFILTER_TITLE _("ITKConfidenceConnectedFilter")
#define SYMBOL_ITKCONFIDENCECONNECTEDFILTER_IDNAME ID_ITKCONFIDENCECONNECTEDFILTER
#define SYMBOL_ITKCONFIDENCECONNECTEDFILTER_SIZE wxSize(200, -1)
#define SYMBOL_ITKCONFIDENCECONNECTEDFILTER_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * ITKConfidenceConnectedFilter class declaration
 */

class ITKConfidenceConnectedFilter: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( ITKConfidenceConnectedFilter )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ITKConfidenceConnectedFilter();
    ITKConfidenceConnectedFilter( wxWindow* parent, wxWindowID id = SYMBOL_ITKCONFIDENCECONNECTEDFILTER_IDNAME, const wxPoint& pos = SYMBOL_ITKCONFIDENCECONNECTEDFILTER_POSITION, const wxSize& size = SYMBOL_ITKCONFIDENCECONNECTEDFILTER_SIZE, long style = SYMBOL_ITKCONFIDENCECONNECTEDFILTER_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_ITKCONFIDENCECONNECTEDFILTER_IDNAME, const wxPoint& pos = SYMBOL_ITKCONFIDENCECONNECTEDFILTER_POSITION, const wxSize& size = SYMBOL_ITKCONFIDENCECONNECTEDFILTER_SIZE, long style = SYMBOL_ITKCONFIDENCECONNECTEDFILTER_STYLE );

    /// Destructor
    ~ITKConfidenceConnectedFilter();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();
	void OnClearSeedsButtonClick( wxCommandEvent& event );
	void OnStartButtonClick( wxCommandEvent& event );
	void OnStopButtonClick( wxCommandEvent& event );
	void OnCloseButtonClick( wxCommandEvent& event );
	void OnSetProgress( wxCommandEvent& event );

////@begin ITKConfidenceConnectedFilter event handler declarations

////@end ITKConfidenceConnectedFilter event handler declarations

////@begin ITKConfidenceConnectedFilter member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ITKConfidenceConnectedFilter member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin ITKConfidenceConnectedFilter member variables
    wxSpinCtrl* mIterations;
    wxTextCtrl* mMultiplier;
    wxGauge* mPercentage;
////@end ITKConfidenceConnectedFilter member variables

    wxWindowDisabler *disabler_;
};

#endif
    // _ITKCONFIDENCECONNECTEDFILTER_H_
