/*
  For more information, please see: http://software.sci.utah.edu
  
  The MIT License

  Copyright (c) 2009 Scientific Computing and Imaging Institute,
  University of Utah.


  Permission is hereby granted, free of charge, to any person obtaining a 
  copy of this software and associated documentation files (the "Software"),
  to deal in the Software without restriction, including without limitation 
  the rights to use, copy, modify, merge, publish, distribute, sublicense, 
  and/or sell copies of the Software, and to permit persons to whom the 
  Software is furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included 
  in all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
  DEALINGS IN THE SOFTWARE.
*/

/////////////////////////////////////////////////////////////////////////////
// Name:        itkneighbourhoodconnectedfilter.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     14/08/2007 13:05:42
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 14/08/2007 13:05:42

#ifndef _ITKNEIGHBOURHOODCONNECTEDFILTER_H_
#define _ITKNEIGHBOURHOODCONNECTEDFILTER_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
////@end includes
#include "wx/spinctrl.h"

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_ITKNEIGHBOURHOODCONNECTEDFILTER 10012
#define SYMBOL_ITKNEIGHBOURHOODCONNECTEDFILTER_STYLE 0
#define SYMBOL_ITKNEIGHBOURHOODCONNECTEDFILTER_TITLE _("ITKNeighbourhoodConnectedFilter")
#define SYMBOL_ITKNEIGHBOURHOODCONNECTEDFILTER_IDNAME ID_ITKNEIGHBOURHOODCONNECTEDFILTER
#define SYMBOL_ITKNEIGHBOURHOODCONNECTEDFILTER_SIZE wxSize(200, -1)
#define SYMBOL_ITKNEIGHBOURHOODCONNECTEDFILTER_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * ITKNeighbourhoodConnectedFilter class declaration
 */

class ITKNeighbourhoodConnectedFilter: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( ITKNeighbourhoodConnectedFilter )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    ITKNeighbourhoodConnectedFilter();
    ITKNeighbourhoodConnectedFilter( wxWindow* parent, wxWindowID id = SYMBOL_ITKNEIGHBOURHOODCONNECTEDFILTER_IDNAME, const wxPoint& pos = SYMBOL_ITKNEIGHBOURHOODCONNECTEDFILTER_POSITION, const wxSize& size = SYMBOL_ITKNEIGHBOURHOODCONNECTEDFILTER_SIZE, long style = SYMBOL_ITKNEIGHBOURHOODCONNECTEDFILTER_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_ITKNEIGHBOURHOODCONNECTEDFILTER_IDNAME, const wxPoint& pos = SYMBOL_ITKNEIGHBOURHOODCONNECTEDFILTER_POSITION, const wxSize& size = SYMBOL_ITKNEIGHBOURHOODCONNECTEDFILTER_SIZE, long style = SYMBOL_ITKNEIGHBOURHOODCONNECTEDFILTER_STYLE );

    /// Destructor
    ~ITKNeighbourhoodConnectedFilter();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();
	void OnClearSeedsButtonClick( wxCommandEvent& event );
	void OnStartButtonClick( wxCommandEvent& event );
	void OnCloseButtonClick( wxCommandEvent& event );
	void OnSetProgress( wxCommandEvent& event );

    void SetShowProgress(bool show_progress);

////@begin ITKNeighbourhoodConnectedFilter event handler declarations

////@end ITKNeighbourhoodConnectedFilter event handler declarations

////@begin ITKNeighbourhoodConnectedFilter member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end ITKNeighbourhoodConnectedFilter member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin ITKNeighbourhoodConnectedFilter member variables
    wxGauge* mPercentage;
////@end ITKNeighbourhoodConnectedFilter member variables

    bool show_progress_;
    wxWindowDisabler *disabler_;
};

#endif
    // _ITKNEIGHBOURHOODCONNECTEDFILTER_H_
