/*
  For more information, please see: http://software.sci.utah.edu
  
  The MIT License

  Copyright (c) 2009 Scientific Computing and Imaging Institute,
  University of Utah.


  Permission is hereby granted, free of charge, to any person obtaining a 
  copy of this software and associated documentation files (the "Software"),
  to deal in the Software without restriction, including without limitation 
  the rights to use, copy, modify, merge, publish, distribute, sublicense, 
  and/or sell copies of the Software, and to permit persons to whom the 
  Software is furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included 
  in all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
  DEALINGS IN THE SOFTWARE.
*/

/////////////////////////////////////////////////////////////////////////////
// Name:        resampletool.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     28/08/2007 06:41:39
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 28/08/2007 06:41:39

#ifndef _RESAMPLETOOL_H_
#define _RESAMPLETOOL_H_

/*!
 * Includes
 */

////@begin includes
#include "wx/xrc/xmlres.h"
#include "wx/spinctrl.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxSpinCtrl;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_RESAMPLETOOL 10035
#define SYMBOL_RESAMPLETOOL_STYLE 0
#define SYMBOL_RESAMPLETOOL_TITLE _("ResampleTool")
#define SYMBOL_RESAMPLETOOL_IDNAME ID_RESAMPLETOOL
#define SYMBOL_RESAMPLETOOL_SIZE wxSize(200, -1)
#define SYMBOL_RESAMPLETOOL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * ResampleTool class declaration
 */

class ResampleTool: public wxPanel
{    
  DECLARE_DYNAMIC_CLASS( ResampleTool )
  DECLARE_EVENT_TABLE()

    public:
  /// Constructors
  ResampleTool();
  ResampleTool( wxWindow* parent, wxWindowID id = SYMBOL_RESAMPLETOOL_IDNAME, const wxPoint& pos = SYMBOL_RESAMPLETOOL_POSITION, const wxSize& size = SYMBOL_RESAMPLETOOL_SIZE, long style = SYMBOL_RESAMPLETOOL_STYLE );

  /// Creation
  bool Create( wxWindow* parent, wxWindowID id = SYMBOL_RESAMPLETOOL_IDNAME, const wxPoint& pos = SYMBOL_RESAMPLETOOL_POSITION, const wxSize& size = SYMBOL_RESAMPLETOOL_SIZE, long style = SYMBOL_RESAMPLETOOL_STYLE );

  /// Destructor
  ~ResampleTool();

  /// Initialises member variables
  void Init();

  /// Creates the controls and sizers
  void CreateControls();
  void OnStartButtonClick( wxCommandEvent& event );
  void OnCloseButtonClick( wxCommandEvent& event );

  ////@begin ResampleTool event handler declarations

  ////@end ResampleTool event handler declarations

  ////@begin ResampleTool member function declarations

  /// Retrieves bitmap resources
  wxBitmap GetBitmapResource( const wxString& name );

  /// Retrieves icon resources
  wxIcon GetIconResource( const wxString& name );
  ////@end ResampleTool member function declarations

  /// Should we show tooltips?
  static bool ShowToolTips();

  ////@begin ResampleTool member variables
  wxSpinCtrl* mX;
  wxSpinCtrl* mY;
  wxSpinCtrl* mZ;
  wxChoice* mFilter;
////@end ResampleTool member variables
};

#endif
// _RESAMPLETOOL_H_
